# Generated by Django 5.1.6 on 2025-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('outdoors', 'Outdoors'), ('games', 'Games'), ('music', 'Music'), ('sports', 'Sports'), ('technology', 'Technology'), ('food', 'Food')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='events.category'),
        ),
    ]
